version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRESS_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"